[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "24.13.0"

[functions]
  directory = "server/.generated/server/functions"

[context.production]
  command = "npm run build:production"
